-- Delete Thomas from private seed str applications
DELETE FROM private_seed_str_applications WHERE email = 'thomas.wenz70@gmail.com';

-- Insert Thomas into seed_str_applications as payment_verified
INSERT INTO seed_str_applications (
  id,
  user_id,
  email,
  full_name,
  investment_amount,
  investment_currency,
  investment_tier,
  str_backing_amount,
  terms_accepted,
  terms_accepted_at,
  nda_accepted,
  nda_accepted_at,
  gdpr_accepted,
  gdpr_accepted_at,
  risk_disclosure_accepted,
  risk_disclosure_accepted_at,
  status,
  payment_status,
  credited_amount,
  str_shares_credited,
  credited_at,
  payment_verified_at,
  application_date,
  created_at,
  updated_at,
  admin_notes
) VALUES (
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'thomas.wenz70@gmail.com',
  'Thomas Claude Wenz',
  66666,
  'USD',
  'retail_tier1',
  400000000,
  true,
  now(),
  true,
  now(),
  true,
  now(),
  true,
  now(),
  'approved',
  'payment_verified',
  400000000,
  66666,
  now(),
  now(),
  now(),
  now(),
  now(),
  'Manually added as payment verified'
);